Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - DivisionAnalyticsSiteConfig
Page:
  extensions:
    - DivisionAnalyticsPageExtension
PageController:
  extensions:
    - DivisionAnalyticsPageControllerExtension
